[workspace]
members = [
  "app",
  "crates/core",
  "crates/tui",
  "crates/adapters",
  "crates/application",
  "crates/gui",
  "gui-app",
]
resolver = "2"

[workspace.package]
version = "0.2.0-alpha.1"
edition = "2021"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
