use super::super::*;
use super::navigation::{ManagerLane, Pane, SchemaColumnViewMode, SchemaLane};
use super::pagination::{PageTransition, PaginationState};
use super::runtime::{ConnectIntent, ConnectWorkerOutcome, ErrorPanel, QueryWorkerOutcome};
use super::wizard::ConnectionWizardForm;

pub(crate) struct TuiApp {
    pub(crate) actions: ActionsEngine,
    pub(crate) pane: Pane,
    pub(crate) wizard_form: ConnectionWizardForm,
    pub(crate) connected_profile: Option<String>,
    pub(crate) last_connection_latency: Option<Duration>,
    pub(crate) data_backend: Option<MysqlDataBackend>,
    pub(crate) schema_cache: Option<SchemaCacheService<MysqlDataBackend>>,
    pub(crate) schema_databases: Vec<String>,
    pub(crate) selected_database_index: usize,
    pub(crate) active_database: Option<String>,
    pub(crate) schema_tables: Vec<String>,
    pub(crate) selected_table_index: usize,
    pub(crate) schema_columns: Vec<String>,
    pub(crate) schema_column_schemas: Vec<ColumnSchema>,
    pub(crate) selected_column_index: usize,
    pub(crate) schema_relationships: Vec<TableRelationship>,
    pub(crate) selected_relationship_index: usize,
    pub(crate) schema_lane: SchemaLane,
    pub(crate) schema_column_view_mode: SchemaColumnViewMode,
    pub(crate) schema_database_filter: String,
    pub(crate) schema_table_filter: String,
    pub(crate) schema_column_filter: String,
    pub(crate) show_help: bool,
    pub(crate) show_palette: bool,
    pub(crate) palette_query: String,
    pub(crate) palette_selection: usize,
    pub(crate) show_perf_overlay: bool,
    pub(crate) last_render_ms: f64,
    pub(crate) recent_render_total_ms: f64,
    pub(crate) recent_render_count: u32,
    pub(crate) fps: f64,
    pub(crate) fps_window_started_at: Instant,
    pub(crate) should_quit: bool,
    pub(crate) query_running: bool,
    pub(crate) query_ticks_remaining: u8,
    pub(crate) safe_mode_guard: SafeModeGuard,
    pub(crate) pending_confirmation: Option<(ConfirmationToken, String)>,
    pub(crate) has_results: bool,
    pub(crate) result_columns: Vec<String>,
    pub(crate) results_cursor: usize,
    pub(crate) results_column_cursor: usize,
    pub(crate) results_search_mode: bool,
    pub(crate) results_search_query: String,
    pub(crate) results: ResultsRingBuffer<QueryRow>,
    pub(crate) pagination_state: Option<PaginationState>,
    pub(crate) pending_page_transition: Option<PageTransition>,
    pub(crate) cancel_requested: bool,
    pub(crate) connect_requested: bool,
    pub(crate) connect_intent: ConnectIntent,
    pub(crate) connect_result_rx: Option<Receiver<ConnectWorkerOutcome>>,
    pub(crate) query_result_rx: Option<Receiver<QueryWorkerOutcome>>,
    pub(crate) query_cancellation: Option<CancellationToken>,
    pub(crate) active_connection_profile: Option<ConnectionProfile>,
    pub(crate) last_connect_profile: Option<ConnectionProfile>,
    pub(crate) pending_retry_query: Option<String>,
    pub(crate) reconnect_attempts: u8,
    pub(crate) query_retry_attempts: u8,
    pub(crate) inflight_query_sql: Option<String>,
    pub(crate) last_failed_query: Option<String>,
    pub(crate) error_panel: Option<ErrorPanel>,
    pub(crate) loading_tick: usize,
    pub(crate) pane_flash_ticks: u8,
    pub(crate) exit_confirmation: bool,
    pub(crate) status_line: String,
    pub(crate) audit_trail: Option<FileAuditTrail>,
    pub(crate) bookmark_store: Option<FileBookmarksStore>,
    pub(crate) profile_store: Option<FileProfilesStore>,
    pub(crate) bookmark_cycle_index: usize,
    pub(crate) manager_lane: ManagerLane,
    pub(crate) manager_profile_cursor: usize,
    pub(crate) manager_bookmark_cursor: usize,
    pub(crate) manager_rename_mode: bool,
    pub(crate) manager_rename_buffer: String,
    pub(crate) query_editor_text: String,
    pub(crate) query_cursor: usize,
    pub(crate) query_history: Vec<String>,
    pub(crate) query_history_index: Option<usize>,
    pub(crate) query_history_draft: Option<String>,
    pub(crate) selection: SchemaSelection,
}
